### ISSUE TITLE
Build fails using ubuntu 16.04 base image

### ISSUE THREAD

**Issue by thomakra** [arrayfire/arrayfire-docker#2]
The repository `ppa:keithw/glfw3` does not provide packages for 16.04 which causes the Docker build to fail.
To get the build to work I had to change the first line in the `Dockerfile` to:

    FROM nvidia/cuda:8.0-devel-ubuntu14.04

so the Trust packages are pulled from the PPA.

**Comment by pavanky** [comment]
@thomakra send in a PR please.

**Comment by thomakra** [comment]
OK, I tried to create a pull request. First ever pull request, hope I didn't mess up.

**Comment by pavanky** [comment]
@thomakra It looked pretty good to me :)
